### ISSUE TITLE
README.md references removed yaml file

### ISSUE THREAD

**Issue by mnigh** [pcraig3/hols#100]
Under the [Push to Cloud Run](https://github.com/pcraig3/hols#push-to-cloud-run) section, `cloudbuild.yaml` links to a removed file from [this commit](https://github.com/pcraig3/hols/commit/9fb05d51b4f3d19b54f3fa782a7727215cb56cef).

**Comment by pcraig3** [comment]
Hello! It's a good point. I will fix the link the next time I do a PR. The `main.yml` workflow is the up to date set of steps, if you were looking for them. Also the CLI command there should also work still.
