### ISSUE TITLE
CalDAV Interface?

### ISSUE THREAD

**Issue by rmclellan** [pcraig3/hols#121]
Any thoughts / interest in adding a CalDAV interface for a continuous calendar as opposed to a yearly download?

**Comment by pcraig3** [comment]
Hello, sorry for the delay here, but I was on a bit of a holiday myself from this site. 

I've had a bit of a look and I am leaning towards not doing a CalDAV feed. It seems like CalDAV is more sophisticated than what I am looking to do here: holidays don't really change very often and there's no way to update them yourself.

There's a sum-up in [this StackOverflow answer](https://stackoverflow.com/questions/30048720/whats-the-difference-between-webcal-and-webdav-caldav/30053513#30053513) I thought was good: 

> In summary: If you simply want to publish a calendar which rarely changes and is managed by other means (like a CMS), you can use iCal-over-HTTP. If you want to provide a calendar which the user (or maybe a group of people) can change from within their calendar client, you want to use CalDAV.

I'm very much in the first category with this one here.

That said, all the data itself is public and accurate, so no worries if you or anyone else wants to piggy back off it.

**Comment by pcraig3** [comment]
Going to close this issue now.
