### ISSUE TITLE
Multiple years with pipe in year parameter does not work

### ISSUE THREAD

**Issue by jpbaril** [pcraig3/hols#139]
Using this does not seem to work anymore:
https://github.com/pcraig3/hols/blob/ae0b1812df4d33e270b913cfa7e25cc54c1f23b8/API.md?plain=1#L57

E.g. [https://canada-holidays.ca/api/v1/holidays?year=2024|2025](https://canada-holidays.ca/api/v1/holidays?year=2024|2025) returns:
```
{
    "error": {
        "status":400,
        "message":"Bad Request: request/query/year must be integer",
        "timestamp":"2024-10-09T20:22:00.149Z"
    }
}
```

**Comment by jpbaril** [comment]
OK, it's not meant to allow multiple years, it's just the possible choices that can be used but only one can be used.

**Comment by pcraig3** [comment]
Thanks for opening the issue, I will change how this is displayed in the documentation.
