### ISSUE TITLE
Function request: nextBusinessDay(String province, Date date)

### ISSUE THREAD

**Issue by denisab85** [pcraig3/hols#57]
Using your API for a test automation project to calculate next business dates. Would be awesome to have a built-in method that would return next non-holiday and non-weekend after a specific date in a specific province.

Thanx! You're making a very useful tool. ))

**Comment by pcraig3** [comment]
Hi there, glad you're getting some use out of it! 👍

Sounds interesting but can you clarify? Right now I'm serving a frontend and a pretty trim API: provinces, holidays, etc. A province can tell you its next holiday, but other than that there's not too much going on. 

Would you expect to be able to get this through an API call or are you cloning the repo and you just want as a function buried somewhere in the code?

**Comment by denisab85** [comment]
I see it as an API call that would return a date.
E.g.:
/api/v1/provinces/MB/nextBusinessDate?after=2020-05-15
would return 2020-05-19 

And the algorithm in the back-end code to process the request would look like so:
weekend[] = {SATURDAY, SUNDAY}
holidays[] = getProvinceHolidays(province, after.getYear())

do {
  after.addDays(1)
} while ( (after IN weekend) or (after IN holidays) )

return after

**Comment by pcraig3** [comment]
Yeah, I could probably get this to work. 

When do you need it for?

**Comment by denisab85** [comment]
Whenever it works for you. I can do with my client side code for now. But as soon as it's implemented in the API, I'll ditch that workaround.
Thanks!

**Comment by pcraig3** [comment]
Hi there @denisab85. Do you still need this? Otherwise, I'm going to close the issue.

**Comment by pcraig3** [comment]
Closing after a few weeks of inaction.
