### ISSUE TITLE
Fetch multiple years (or range)

### ISSUE THREAD

**Issue by Sebjugate** [pcraig3/hols#90]
Thanks for this API, it is exactly what I am looking for!

I'm using it to feed a BI report, so hitting it very rarely, but I'd like to be able to fetch all holidays within the past X years in one query.

If it's possible, I'm happy with whatever you think is best, but I was thinking the most flexible might be to add a rangeStart and rangeEnd parameter?

**Comment by pcraig3** [comment]
Hello!

Thanks for the question, here's where I'm at with this. 

One of my core architectural assumptions is that I calculating all the holidays for one year at a time. It wouldn't be impossible to make the change you're suggesting, but the API and frontend that are both running off the same backend logic in [`getHolidays`](https://github.com/pcraig3/hols/blob/73d0ce53dbbee56acea50289545fc9a437de1da6/src/queries/index.js#L43), which which always returns all the holidays for 1 year. Almost all my routes are using this one function (defaulting to the current year if there is no explicit parameter). 

That's not a 'no', instead it's an "are you sure you need it?". For me, I can see the value but it's a reasonably hard change to make at this point. My previous stance on this has been "just make a few calls in a row on your end" and I can keep the interface simple. 

Are you able to get by just making a few consecutive calls?

**Comment by Sebjugate** [comment]
I see, that makes sense. I will check whether I can fetch years one at a time. I am trying to use it as a data source in Power BI. Let me do some fiddling and get back to you. I will reopen if necessary.

**Comment by jjtagh** [comment]
@Sebjugate or the next person- I had this same challenge working in Power Query in Excel. Here's what I did:
1) Create parameters for this year and next (You could write a function if you have multiple or changing years)
	
```
ThisYear= Text.From( Date.Year( Date.From(DateTime.LocalNow() ))) 
NextYear= Text.From( Date.Year( Date.AddYears(  Date.From(DateTime.LocalNow() ), 1 )))
```

2) Setup a parameter table:

```
Years = #table(
        type table
            [ 
                #"Year"=text
            ],
        {
            {ThisYear}, 
            {NextYear}
        } 
)
```
*you need to explicitly type the table or else Power Query assigns the ABC123 'Any' type which breaks the input parameter in the next step (Year as text). 

3) Create a function to pass in the criteria:
	
` GetHolidays = (Year as text) => Json.Document( Web.Contents(_Your API request string with your criteria_))`

4) Loop through the Years table with the GetHolidays function

`HolidaySet= Table.AddColumn(Years, "HolidaySet", each GetHolidays([Year]))`

Now you should end up with a new column of Records for each holiday that you can proceed to transform.
